import type { LessonInput } from '../../schema';

export const idempotencyLesson: LessonInput = {
  tier: 'lesson',
  slug: 'idempotency',
  title: 'Idempotency and Retries',
  summary: 'Every network call can be retried; make sure the second one is harmless.',
  order: 11,
  track: 'system-design',
  difficulty: 'advanced',

  operations: [
    { name: 'idempotency key lookup', time: '1-2 ms', note: 'One store read on the write path. Cheap insurance.' },
    { name: 'key retention', time: '24-72 h', note: 'Long enough to cover any retry a client will realistically make.' },
    { name: 'retry with exponential backoff', time: '2^n x base + jitter', note: 'Jitter matters as much as backoff — without it, retries synchronise.' },
    { name: 'circuit breaker open', time: '10-60 s', note: 'Stop calling a failing dependency and let it recover.' },
  ],

  concepts: ['idempotency', 'metrics-logs-traces', 'slo', 'percentiles'],

  variants: [
    { name: 'Naturally idempotent', what: 'PUT, DELETE, "set status to shipped". Repeating changes nothing.' },
    { name: 'Idempotency key', what: 'The client sends a unique id; the server stores the result and replays it on retry. What payment APIs do.' },
    { name: 'Deduplication window', what: 'Ignore a repeated message id seen recently. Cheaper, and only correct within the window.' },
    { name: 'Optimistic concurrency', what: 'Include the version you read; the write fails if it changed. Turns a lost update into a visible conflict.' },
  ],

  furtherReading: [
    { label: 'Idempotence', url: 'https://en.wikipedia.org/wiki/Idempotence', source: 'Wikipedia' },
    { label: 'Exponential backoff', url: 'https://en.wikipedia.org/wiki/Exponential_backoff', source: 'Wikipedia' },
    { label: 'Circuit breaker pattern', url: 'https://en.wikipedia.org/wiki/Circuit_breaker_design_pattern', source: 'Wikipedia' },
  ],

  explainer: `A network call that times out has an unknown outcome. It may have failed before
arriving, or succeeded with the response lost on the way back. The client cannot
tell the difference, so it retries — and if the operation was "charge this card",
the customer is charged twice.

This is not an edge case. It is the normal behaviour of every distributed system,
and it is why **at-least-once delivery plus idempotent handlers** is the standard
design rather than chasing exactly-once semantics that do not exist.

**Idempotent** means performing the operation twice has the same effect as once.
Some operations already are: setting a value, deleting a record, marking an order
shipped. Others are not: incrementing a counter, appending to a list, charging a
card.

For those, the standard mechanism is an **idempotency key**. The client generates
a unique id for the *intent* and sends it with the request. The server records
the key with the result of the first execution; a repeat with the same key
returns the stored result without doing the work again. Two details decide
whether it works: the key must be generated by the client before the first
attempt — a server-generated one is different on every retry, which defeats it —
and storing the key must be atomic with performing the operation, or a crash in
between produces exactly the double-charge you were preventing.

**Retries need discipline of their own.** Exponential backoff spreads attempts
out; **jitter** is what stops every client retrying at the same instant and
turning a brief blip into a thundering herd. And retries need a stopping
condition: a **circuit breaker** that stops calling a dependency which is clearly
down, so you stop adding load to something already struggling.

One rule worth stating plainly: **only retry idempotent operations
automatically.** Retrying a non-idempotent call is how a single timeout becomes a
duplicate charge.`,

  whenToUse: {
    reachFor: [
      'Payments, orders, and anything that moves money or allocates a limited resource.',
      'Any consumer of an at-least-once queue, which will redeliver eventually.',
      'Public APIs where clients you do not control will retry however they like.',
      'Webhook receivers — providers retry aggressively and duplicates are guaranteed.',
    ],
    insteadOf: [
      { alternative: 'Exactly-once delivery', why: 'It does not exist across a network in the general case. At-least-once with idempotent handlers is the achievable version of the same guarantee, and simpler than pretending otherwise.' },
      { alternative: 'Distributed transactions', why: 'Two-phase commit gives atomicity across services by holding locks across the network, which harms availability. A saga of idempotent steps with compensating actions is the usual trade.' },
      { alternative: 'Never retrying', why: 'Avoids duplicates by turning every transient blip into a user-visible failure. Retries are how a system survives an unreliable network; idempotency is what makes them safe.' },
    ],
  },

  patternCues: [
    'The operation charges, books, or allocates something finite.',
    'The design includes a queue, which will redeliver.',
    'The interviewer asks what happens if the request times out.',
    'You are receiving webhooks from a third party.',
  ],

  pitfalls: [
    { title: 'Server-generated idempotency keys', body: 'A key created on the server differs on every retry, so nothing is deduplicated. The client must generate it before the first attempt.' },
    { title: 'Storing the key separately from the effect', body: 'If the operation succeeds and recording the key fails, the retry runs it again. They must commit together.' },
    { title: 'Retrying without jitter', body: 'Synchronised retries turn a brief outage into a self-inflicted denial of service the moment the service recovers.' },
    { title: 'Retrying non-idempotent operations automatically', body: 'This is the double-charge, and it is usually a client-library default rather than a deliberate decision.' },
  ],

  recommendedAfter: ['message-queues'],
};
