import type { CanvasArchitecture, ComponentTemplate } from './canvas-types';

/**
 * Standard palette component templates for System Design architecture canvas (C1).
 */
export const COMPONENT_TEMPLATES: ComponentTemplate[] = [
  // ── Client & Edge ──────────────────────────────────────────────────────────
  {
    type: 'web-client',
    label: 'Web Client',
    category: 'client',
    description: 'Single-page web applications and browsers.',
    icon: 'globe',
    conceptSlug: 'latency-vs-throughput',
    defaultMetrics: { qps: 10000, latencyMs: 30 },
  },
  {
    type: 'mobile-client',
    label: 'Mobile App',
    category: 'client',
    description: 'iOS and Android client applications.',
    icon: 'smartphone',
    conceptSlug: 'latency-vs-throughput',
    defaultMetrics: { qps: 25000, latencyMs: 80 },
  },
  {
    type: 'cdn',
    label: 'CDN Edge',
    category: 'edge',
    description: 'Geo-distributed edge caching network (Cloudflare/CloudFront).',
    icon: 'cloud',
    conceptSlug: 'cdn',
    defaultMetrics: { qps: 35000, latencyMs: 15, hitRatePercent: 85 },
  },
  {
    type: 'load-balancer',
    label: 'Load Balancer',
    category: 'edge',
    description: 'L7 Reverse Proxy & Traffic Distributor (ALB / Nginx).',
    icon: 'split',
    conceptSlug: 'load-balancer',
    defaultMetrics: { qps: 35000, latencyMs: 2 },
  },
  {
    type: 'api-gateway',
    label: 'API Gateway',
    category: 'edge',
    description: 'Unified client entrypoint with auth, routing, and throttling.',
    icon: 'shield',
    conceptSlug: 'api-gateway',
    defaultMetrics: { qps: 35000, latencyMs: 5 },
  },

  // ── Compute & Services ─────────────────────────────────────────────────────
  {
    type: 'app-server',
    label: 'App Server Cluster',
    category: 'compute',
    description: 'Stateless application service instances running business logic.',
    icon: 'server',
    conceptSlug: 'vertical-vs-horizontal',
    defaultMetrics: { qps: 15000, latencyMs: 15, replicationCount: 5 },
  },
  {
    type: 'microservice',
    label: 'Core Microservice',
    category: 'compute',
    description: 'Domain-specific service executing bounded workflows.',
    icon: 'cpu',
    conceptSlug: 'api-gateway',
    defaultMetrics: { qps: 8000, latencyMs: 10, replicationCount: 3 },
  },
  {
    type: 'async-worker',
    label: 'Background Worker',
    category: 'compute',
    description: 'Asynchronous task processors consuming jobs from queues.',
    icon: 'cog',
    conceptSlug: 'competing-consumers',
    defaultMetrics: { qps: 2000, latencyMs: 250, replicationCount: 4 },
  },

  // ── Caching ────────────────────────────────────────────────────────────────
  {
    type: 'redis-cache',
    label: 'Redis Cache',
    category: 'cache',
    description: 'In-memory key-value cache layer mitigating database read load.',
    icon: 'zap',
    conceptSlug: 'cache-aside',
    defaultMetrics: { qps: 30000, latencyMs: 1, hitRatePercent: 90, storageGb: 64 },
  },
  {
    type: 'distributed-cache',
    label: 'Distributed Cache Cluster',
    category: 'cache',
    description: 'Sharded cache with consistent hashing and active replicas.',
    icon: 'layers',
    conceptSlug: 'consistent-hashing',
    defaultMetrics: { qps: 80000, latencyMs: 2, hitRatePercent: 95, storageGb: 256, replicationCount: 3 },
  },

  // ── Data Stores ────────────────────────────────────────────────────────────
  {
    type: 'postgres-primary',
    label: 'SQL DB (Primary)',
    category: 'database',
    description: 'ACID-compliant relational database accepting writes.',
    icon: 'database',
    conceptSlug: 'sql-vs-nosql',
    defaultMetrics: { qps: 3000, latencyMs: 10, storageGb: 500 },
  },
  {
    type: 'postgres-replica',
    label: 'SQL DB (Read Replica)',
    category: 'database',
    description: 'Asynchronously replicated database serving read queries.',
    icon: 'database',
    conceptSlug: 'read-replicas',
    defaultMetrics: { qps: 12000, latencyMs: 8, storageGb: 500, replicationCount: 2 },
  },
  {
    type: 'nosql-kv',
    label: 'NoSQL Store (DynamoDB)',
    category: 'database',
    description: 'Horizontally scalable key-value / document database.',
    icon: 'table',
    conceptSlug: 'sql-vs-nosql',
    defaultMetrics: { qps: 40000, latencyMs: 5, storageGb: 2000 },
  },
  {
    type: 'object-storage',
    label: 'Blob Storage (S3)',
    category: 'database',
    description: 'High-durability storage for images, videos, and raw payloads.',
    icon: 'hard-drive',
    conceptSlug: 'claim-check',
    defaultMetrics: { qps: 5000, latencyMs: 40, storageGb: 50000 },
  },
  {
    type: 'search-engine',
    label: 'Search Index (Elasticsearch)',
    category: 'database',
    description: 'Distributed inverted index for full-text search and aggregations.',
    icon: 'search',
    conceptSlug: 'secondary-index',
    defaultMetrics: { qps: 4000, latencyMs: 20, storageGb: 300 },
  },

  // ── Messaging & Streaming ──────────────────────────────────────────────────
  {
    type: 'message-queue',
    label: 'Message Queue (SQS / RabbitMQ)',
    category: 'queue',
    description: 'FIFO or standard queue for point-to-point task decoupling.',
    icon: 'mail',
    conceptSlug: 'dead-letter',
    defaultMetrics: { qps: 10000, latencyMs: 15 },
  },
  {
    type: 'event-stream',
    label: 'Event Stream (Kafka)',
    category: 'queue',
    description: 'Partitioned, durable append-only log for high-throughput streaming.',
    icon: 'activity',
    conceptSlug: 'consumer-group',
    defaultMetrics: { qps: 60000, latencyMs: 5, replicationCount: 3 },
  },

  // ── Reliability & Defense ──────────────────────────────────────────────────
  {
    type: 'rate-limiter',
    label: 'Rate Limiter',
    category: 'reliability',
    description: 'Token bucket / sliding window limiter protecting downstream resources.',
    icon: 'gauge',
    conceptSlug: 'rate-limiting',
    defaultMetrics: { qps: 35000, latencyMs: 1 },
  },
  {
    type: 'circuit-breaker',
    label: 'Circuit Breaker',
    category: 'reliability',
    description: 'Fails fast when downstream services are degraded to prevent cascading collapse.',
    icon: 'alert-triangle',
    conceptSlug: 'circuit-breaker-pattern',
    defaultMetrics: { qps: 15000, latencyMs: 1 },
  },
];

/**
 * Curated architecture presets matching standard interview scenarios.
 */
export const ARCHITECTURE_PRESETS: Record<string, CanvasArchitecture> = {
  'url-shortener': {
    title: 'URL Shortener (TinyURL)',
    description: 'High read-to-write ratio (100:1) with global CDN, API gateway, Redis caching, and PostgreSQL primary/replica pair.',
    nodes: [
      {
        id: 'client-1',
        type: 'web-client',
        label: 'Clients',
        category: 'client',
        x: 60,
        y: 180,
        icon: 'globe',
        conceptSlug: 'latency-vs-throughput',
        metrics: { qps: 100000, latencyMs: 30 },
      },
      {
        id: 'cdn-1',
        type: 'cdn',
        label: 'Global CDN',
        category: 'edge',
        x: 240,
        y: 180,
        icon: 'cloud',
        conceptSlug: 'cdn',
        metrics: { qps: 100000, latencyMs: 10, hitRatePercent: 70 },
      },
      {
        id: 'lb-1',
        type: 'load-balancer',
        label: 'Load Balancer (ALB)',
        category: 'edge',
        x: 420,
        y: 180,
        icon: 'split',
        conceptSlug: 'load-balancer',
        metrics: { qps: 30000, latencyMs: 2 },
      },
      {
        id: 'app-1',
        type: 'app-server',
        label: 'URL Shortener API',
        category: 'compute',
        x: 600,
        y: 180,
        icon: 'server',
        conceptSlug: 'vertical-vs-horizontal',
        metrics: { qps: 30000, latencyMs: 12, replicationCount: 6 },
      },
      {
        id: 'cache-1',
        type: 'redis-cache',
        label: 'Redis Cache (Top URLs)',
        category: 'cache',
        x: 780,
        y: 90,
        icon: 'zap',
        conceptSlug: 'cache-aside',
        metrics: { qps: 29000, latencyMs: 2, hitRatePercent: 90 },
      },
      {
        id: 'db-primary',
        type: 'postgres-primary',
        label: 'PostgreSQL Primary (Writes)',
        category: 'database',
        x: 780,
        y: 270,
        icon: 'database',
        conceptSlug: 'sql-vs-nosql',
        metrics: { qps: 1000, latencyMs: 15, storageGb: 500 },
      },
      {
        id: 'db-replica',
        type: 'postgres-replica',
        label: 'PostgreSQL Replicas (Reads)',
        category: 'database',
        x: 960,
        y: 270,
        icon: 'database',
        conceptSlug: 'read-replicas',
        metrics: { qps: 3000, latencyMs: 8, storageGb: 500, replicationCount: 2 },
      },
    ],
    edges: [
      { id: 'e1', sourceId: 'client-1', targetId: 'cdn-1', label: 'HTTPS', protocol: 'https' },
      { id: 'e2', sourceId: 'cdn-1', targetId: 'lb-1', label: 'Cache Miss', protocol: 'https' },
      { id: 'e3', sourceId: 'lb-1', targetId: 'app-1', label: 'HTTP / JSON', protocol: 'https' },
      { id: 'e4', sourceId: 'app-1', targetId: 'cache-1', label: 'Cache Lookups', protocol: 'tcp' },
      { id: 'e5', sourceId: 'app-1', targetId: 'db-primary', label: 'New URL Writes', protocol: 'sql' },
      { id: 'e6', sourceId: 'db-primary', targetId: 'db-replica', label: 'Async Replication', protocol: 'sql', animated: true },
      { id: 'e7', sourceId: 'app-1', targetId: 'db-replica', label: 'Cache Miss Reads', protocol: 'sql' },
    ],
  },

  'rate-limiter': {
    title: 'Distributed Rate Limiter',
    description: 'High-throughput token bucket / sliding window limiter with API gateway middleware, Redis cluster, and asynchronous telemetry aggregation.',
    nodes: [
      {
        id: 'client-1',
        type: 'web-client',
        label: 'Public Clients',
        category: 'client',
        x: 60,
        y: 180,
        icon: 'globe',
        conceptSlug: 'latency-vs-throughput',
        metrics: { qps: 500000, latencyMs: 25 },
      },
      {
        id: 'gw-1',
        type: 'api-gateway',
        label: 'API Gateway',
        category: 'edge',
        x: 260,
        y: 180,
        icon: 'shield',
        conceptSlug: 'api-gateway',
        metrics: { qps: 500000, latencyMs: 3 },
      },
      {
        id: 'limiter-1',
        type: 'rate-limiter',
        label: 'Limiter Middleware',
        category: 'reliability',
        x: 460,
        y: 180,
        icon: 'gauge',
        conceptSlug: 'rate-limiting',
        metrics: { qps: 500000, latencyMs: 1 },
      },
      {
        id: 'redis-cluster',
        type: 'distributed-cache',
        label: 'Redis Cluster (Counters)',
        category: 'cache',
        x: 460,
        y: 340,
        icon: 'layers',
        conceptSlug: 'consistent-hashing',
        metrics: { qps: 500000, latencyMs: 1, replicationCount: 3 },
      },
      {
        id: 'backend-1',
        type: 'app-server',
        label: 'Backend Microservices',
        category: 'compute',
        x: 680,
        y: 180,
        icon: 'server',
        conceptSlug: 'vertical-vs-horizontal',
        metrics: { qps: 450000, latencyMs: 20, replicationCount: 12 },
      },
      {
        id: 'queue-1',
        type: 'message-queue',
        label: 'Audit & Telemetry Queue',
        category: 'queue',
        x: 680,
        y: 340,
        icon: 'mail',
        conceptSlug: 'dead-letter',
        metrics: { qps: 50000, latencyMs: 10 },
      },
    ],
    edges: [
      { id: 'e1', sourceId: 'client-1', targetId: 'gw-1', label: 'HTTP / API', protocol: 'https' },
      { id: 'e2', sourceId: 'gw-1', targetId: 'limiter-1', label: 'Filter Pipeline', protocol: 'grpc' },
      { id: 'e3', sourceId: 'limiter-1', targetId: 'redis-cluster', label: 'Lua Script Token Bucket', protocol: 'tcp' },
      { id: 'e4', sourceId: 'limiter-1', targetId: 'backend-1', label: 'Allowed (200 OK)', protocol: 'grpc' },
      { id: 'e5', sourceId: 'limiter-1', targetId: 'queue-1', label: 'Throttled Events (429)', protocol: 'pubsub' },
    ],
  },

  'video-streaming': {
    title: 'Video Streaming Platform (YouTube/Netflix)',
    description: 'Video upload and playback pipeline featuring chunking, async worker queues, blob storage, and CDN edge delivery.',
    nodes: [
      {
        id: 'creator-1',
        type: 'web-client',
        label: 'Video Creator',
        category: 'client',
        x: 60,
        y: 100,
        icon: 'globe',
        conceptSlug: 'latency-vs-throughput',
        metrics: { qps: 500, latencyMs: 50 },
      },
      {
        id: 'viewer-1',
        type: 'mobile-client',
        label: 'Video Viewers',
        category: 'client',
        x: 60,
        y: 280,
        icon: 'smartphone',
        conceptSlug: 'latency-vs-throughput',
        metrics: { qps: 200000, latencyMs: 40 },
      },
      {
        id: 'lb-1',
        type: 'load-balancer',
        label: 'Ingestion Load Balancer',
        category: 'edge',
        x: 240,
        y: 100,
        icon: 'split',
        conceptSlug: 'load-balancer',
        metrics: { qps: 500, latencyMs: 3 },
      },
      {
        id: 'cdn-1',
        type: 'cdn',
        label: 'Video Delivery CDN',
        category: 'edge',
        x: 240,
        y: 280,
        icon: 'cloud',
        conceptSlug: 'cdn',
        metrics: { qps: 200000, latencyMs: 15, hitRatePercent: 95 },
      },
      {
        id: 'ingest-1',
        type: 'app-server',
        label: 'Upload Service',
        category: 'compute',
        x: 420,
        y: 100,
        icon: 'server',
        conceptSlug: 'vertical-vs-horizontal',
        metrics: { qps: 500, latencyMs: 25 },
      },
      {
        id: 'queue-transcode',
        type: 'message-queue',
        label: 'Transcoding Queue',
        category: 'queue',
        x: 600,
        y: 100,
        icon: 'mail',
        conceptSlug: 'dead-letter',
        metrics: { qps: 500, latencyMs: 15 },
      },
      {
        id: 'worker-transcode',
        type: 'async-worker',
        label: 'FFmpeg Transcoder Fleet',
        category: 'compute',
        x: 780,
        y: 100,
        icon: 'cog',
        conceptSlug: 'competing-consumers',
        metrics: { qps: 500, latencyMs: 5000, replicationCount: 16 },
      },
      {
        id: 's3-chunks',
        type: 'object-storage',
        label: 'S3 (HLS Video Chunks)',
        category: 'database',
        x: 600,
        y: 280,
        icon: 'hard-drive',
        conceptSlug: 'claim-check',
        metrics: { qps: 10000, latencyMs: 25, storageGb: 100000 },
      },
      {
        id: 'meta-db',
        type: 'postgres-primary',
        label: 'Video Metadata DB',
        category: 'database',
        x: 420,
        y: 280,
        icon: 'database',
        conceptSlug: 'sql-vs-nosql',
        metrics: { qps: 5000, latencyMs: 10, storageGb: 1000 },
      },
    ],
    edges: [
      { id: 'e1', sourceId: 'creator-1', targetId: 'lb-1', label: 'Upload Video Chunk', protocol: 'https' },
      { id: 'e2', sourceId: 'lb-1', targetId: 'ingest-1', label: 'Stream Payload', protocol: 'https' },
      { id: 'e3', sourceId: 'ingest-1', targetId: 'queue-transcode', label: 'Enqueue Job', protocol: 'pubsub' },
      { id: 'e4', sourceId: 'queue-transcode', targetId: 'worker-transcode', label: 'Pull Task', protocol: 'pubsub' },
      { id: 'e5', sourceId: 'worker-transcode', targetId: 's3-chunks', label: 'Store 1080p/720p/4K Chunks', protocol: 'https' },
      { id: 'e6', sourceId: 'worker-transcode', targetId: 'meta-db', label: 'Save Manifest URL', protocol: 'sql' },
      { id: 'e7', sourceId: 'viewer-1', targetId: 'cdn-1', label: 'Play HLS Stream (.m3u8)', protocol: 'https' },
      { id: 'e8', sourceId: 'cdn-1', targetId: 's3-chunks', label: 'Origin Pull', protocol: 'https' },
    ],
  },
  'distributed-cache': {
    title: 'Distributed In-Memory Cache',
    description: 'High-throughput in-memory caching tier with consistent hashing router, sharded Redis nodes, and persistent database backing.',
    nodes: [
      {
        id: 'client-svc',
        type: 'app-server',
        label: 'API Service',
        category: 'compute',
        x: 60,
        y: 180,
        icon: 'server',
        conceptSlug: 'vertical-vs-horizontal',
        metrics: { qps: 45000, latencyMs: 5 },
      },
      {
        id: 'router-1',
        type: 'load-balancer',
        label: 'Consistent Hashing Router',
        category: 'edge',
        x: 240,
        y: 180,
        icon: 'split',
        conceptSlug: 'consistent-hashing',
        metrics: { qps: 45000, latencyMs: 1 },
      },
      {
        id: 'cache-shard-1',
        type: 'redis-cache',
        label: 'Cache Node A (0 - 180°)',
        category: 'cache',
        x: 440,
        y: 80,
        icon: 'zap',
        conceptSlug: 'cache-aside',
        metrics: { qps: 22000, latencyMs: 1, hitRatePercent: 92, storageGb: 64 },
      },
      {
        id: 'cache-shard-2',
        type: 'redis-cache',
        label: 'Cache Node B (180° - 360°)',
        category: 'cache',
        x: 440,
        y: 280,
        icon: 'zap',
        conceptSlug: 'cache-aside',
        metrics: { qps: 23000, latencyMs: 1, hitRatePercent: 92, storageGb: 64 },
      },
      {
        id: 'db-primary',
        type: 'postgres-primary',
        label: 'Primary SQL Store',
        category: 'database',
        x: 640,
        y: 180,
        icon: 'database',
        conceptSlug: 'sql-vs-nosql',
        metrics: { qps: 4000, latencyMs: 12, storageGb: 500 },
      },
    ],
    edges: [
      { id: 'e1', sourceId: 'client-svc', targetId: 'router-1', label: 'Key Hash Lookup', protocol: 'grpc' },
      { id: 'e2', sourceId: 'router-1', targetId: 'cache-shard-1', label: 'Ring Sector A', protocol: 'tcp' },
      { id: 'e3', sourceId: 'router-1', targetId: 'cache-shard-2', label: 'Ring Sector B', protocol: 'tcp' },
      { id: 'e4', sourceId: 'cache-shard-1', targetId: 'db-primary', label: 'Cache Miss Fallback', protocol: 'sql' },
      { id: 'e5', sourceId: 'cache-shard-2', targetId: 'db-primary', label: 'Cache Miss Fallback', protocol: 'sql' },
    ],
  },
  'real-time-chat': {
    title: 'Real-Time Messaging (Chat / Presence)',
    description: 'Stateful WebSocket connection tier with Redis Pub/Sub fanout, Kafka append-only log, and Cassandra archive.',
    nodes: [
      {
        id: 'chat-client',
        type: 'mobile-client',
        label: 'Chat Clients',
        category: 'client',
        x: 60,
        y: 180,
        icon: 'smartphone',
        conceptSlug: 'latency-vs-throughput',
        metrics: { qps: 30000, latencyMs: 20 },
      },
      {
        id: 'ws-gateway',
        type: 'api-gateway',
        label: 'WebSocket Gateway Cluster',
        category: 'edge',
        x: 240,
        y: 180,
        icon: 'shield',
        conceptSlug: 'api-gateway',
        metrics: { qps: 30000, latencyMs: 2 },
      },
      {
        id: 'redis-presence',
        type: 'redis-cache',
        label: 'Redis Pub/Sub & Presence',
        category: 'cache',
        x: 420,
        y: 80,
        icon: 'zap',
        conceptSlug: 'pub-sub',
        metrics: { qps: 50000, latencyMs: 1, storageGb: 32 },
      },
      {
        id: 'kafka-events',
        type: 'event-stream',
        label: 'Message Event Log (Kafka)',
        category: 'queue',
        x: 420,
        y: 280,
        icon: 'activity',
        conceptSlug: 'consumer-group',
        metrics: { qps: 30000, latencyMs: 3 },
      },
      {
        id: 'chat-archive',
        type: 'nosql-kv',
        label: 'Message Archive (Cassandra)',
        category: 'database',
        x: 620,
        y: 280,
        icon: 'table',
        conceptSlug: 'sql-vs-nosql',
        metrics: { qps: 15000, latencyMs: 6, storageGb: 5000 },
      },
    ],
    edges: [
      { id: 'e1', sourceId: 'chat-client', targetId: 'ws-gateway', label: 'WSS Persistent', protocol: 'websocket' },
      { id: 'e2', sourceId: 'ws-gateway', targetId: 'redis-presence', label: 'Heartbeat & Channel Fanout', protocol: 'tcp' },
      { id: 'e3', sourceId: 'ws-gateway', targetId: 'kafka-events', label: 'Emit Chat Message', protocol: 'pubsub' },
      { id: 'e4', sourceId: 'kafka-events', targetId: 'chat-archive', label: 'Persist History', protocol: 'tcp' },
    ],
  },
};
